name: Code Checking

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  checking:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.x

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Checking TypeScript
        run: npm run typecheck
